"""write a program to print all subsequence of string which start with vowel and end with consonant
given a string return all possible subsequences which start with vowel and end with a consonant.A string is a
subsequence of a given string,that is generated by deleting some character of a given string without changing its order
"""
def start(vowels):
    str1="abcefg"
    for i in range(0,len(str1)):
        if str1[i] in vowels:
            start_index=i
            for j in range(i+1,len(str1)):
                if str1[j] not in vowels:
                    end_index=j
                else:
                    end_index=j-1
                    break
            rules(start_index,end_index,str1)

def rules(start_index,end_index,str1):
    print(start_index,end_index)
    for k in range(start_index,end_index):
        print(str1[start_index]+str1[k+1],end=' ')
    print(str1[start_index:end_index+1])

start("aeiou")
